### your site title here

title: Elliptic-Py Docs
baseurl: https://justvdnsh.github.io/elliptic-py # name of the repository
email: justdvnsh2208@gmail.com



highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
analytics: "UA-120388254-1"

# Comments
disqus-shortname: "divyansh"



#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]